# .github/workflows/test-api.yml
name: API Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install pytest

      - name: Run API unit tests
        run: |
          cd api
          python -m pytest test_api.py -v --tb=short